---
- name: add microsoft package repo
  sudo: yes
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial main
    state: present

- name: install dotnet core
  sudo: yes
  apt: 
    name: dotnet-sdk-2.0.0
    state: present